#!/usr/bin/env zsh

# unixy
alias ll='ls -lah'
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'

# shortcuts to editing
alias vimrc='vim ~/.vimrc'
alias zshrc='vim ~/.zshrc'
alias zalias='vim ~/.zalias'

# reloading
alias zaliasr='source ~/.zalias'

# git
alias gbcl="git branch --merged master | grep -v 'master$' | xargs git branch -d"
alias gpoh="git push -u origin HEAD"

# react native
alias rna='react-native run-android'
alias rni='reattach-to-user-namespace react-native run-ios'
alias rnise='reattach-to-user-namespace react-native run-ios --simulator "iPhone SE"'
alias rni7='reattach-to-user-namespace react-native run-ios --simulator "iPhone 7"'
alias rni7p='reattach-to-user-namespace react-native run-ios --simulator "iPhone 7 Plus"'
alias rns='react-native start'
alias shake='npm run android:shake'

# yarn
alias y='yarn'
alias ya='yarn add'
alias yga='yarn global add'
alias yr='yarn run'
alias ys='yarn start'
alias yout='yarn outdated'
alias yt='yarn test'
alias yrb='yarn run build'
alias yrl='yarn run lint'
alias yrw='yarn run watch'
alias yu='yarn upgrade'

