#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  colorscheme = "gruvbox"
  background = "dark"
  enable_guicolors = true
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_display_mode = false
  bootstrap_after = "myspacevim#after"

[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behaviour = "complete"
  auto-completion-tab-key-behaviour = "smart"

[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 30

[[layers]]
  name = "tmux"

[[layers]]
  name = "fzf"

[[layers]]
  name = "tags"

[[layers]]
  name = "colorscheme"

#[[layers]]
#  name = "ctrlp"

[[custom_plugins]]
  name = "dag/vim-fish"

[[custom_plugins]]
  name = "alaviss/nim.nvim"
#  name = "zah/nim.vim"

[[custom_plugins]]
  name = "vmchale/just-vim"

